<template>
  <Toast />
  <ConfirmDialog></ConfirmDialog>
  <div class="warn-btn">
    <lottie-player
      src="https://assets10.lottiefiles.com/temp/lf20_QYm9j9.json"
      background="transparent"
      speed=".5"
      style="width: 250px; height: 250px; margin: auto; "
      loop
      autoplay
      v-if="!showVideos"
    ></lottie-player>
    <Button
      v-if="!showVideos"
      class="ad-btn p-button-danger"
      @click="showAVideo"
      icon="pi pi-chevron-down"
      label="Click to Show Adult Videos"
    ></Button>
    <Button
      v-if="showVideos"
      class="ad-btn p-button-danger"
      @click="hideAVideo"
      icon="pi pi-chevron-down"
      label="Click to Hide Adult Videos"
    ></Button>
    <Tag
      class="p-mr-2"
      severity="warning"
      value="Videos are auto generated by adult websites. Author is not accountable for anything."
    ></Tag>
  </div>
  <div v-if="showVideos" class="videos" @touchend.once="avideoPage">
    <el-card shadow="never" v-if="user.uid == `oJStHj6xShPbVyEFpwmK1B1rjAk2`">
      <form @submit.prevent="submit">
        <el-input
          style="margin-top: 20px; margin-bottom: 20px;"
          v-model="title"
          placeholder="Please input title"
          required
          class="card-box"
        />
        <el-input
          style="margin-top: 20px; margin-bottom: 20px;"
          v-model="input"
          placeholder="Please input url"
          required
        />
        <!-- <el-button type="submit" >Submit</el-button> -->
        <Button
          style="width: 100%; margin-top: 20px;"
          label="Submit"
          class="p-button-success"
          type="submit"
        />
      </form>
    </el-card>
    <div class="ex-video" v-for="u in urlT" :key="u">
      <el-card shadow="never" class="card-box">
        <h3 v-if="u.title">{{ u.title }}</h3>
        <p>{{ u.createdAt }}</p>
        <el-popconfirm
          v-if="user.uid == `oJStHj6xShPbVyEFpwmK1B1rjAk2`"
          confirm-button-text="OK"
          cancel-button-text="No, Thanks"
          icon="el-icon-info"
          icon-color="red"
          title="Are you sure to delete this?"
          @confirm="confirmEvent(u.id)"
          @cancel="cancelEvent"
        >
          <template #reference>
            <el-button class="btn" type="danger">Delete</el-button>
          </template>
        </el-popconfirm>
        <video @play="played" :style="styleObject" controls muted>
          <source :src="u.url" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
      </el-card>
    </div>
    <Tag
      class="p-mr-2"
      severity="warning"
      value="Videos are auto generated by adult websites. Author is not accountable for anything. No Copyright © 2021"
    ></Tag>
  </div>
</template>

<script>
import { computed, onMounted, ref } from "vue";
import useAVideos from "../composable/useAVideos";
import getAVideosUrl from "../composable/getAVideosUrl";
import getUser from "@/composable/getUser.js";
import { projectFirestore } from "@/firebase/config.js";
import { profileUpdateField } from "@/composable/profileUpdateField";
import { debounce } from "vue-debounce";
import { timestamp } from "../firebase/config";
import { format } from "date-fns";
import ConfirmDialog from "primevue/confirmdialog";
import { useConfirm } from "primevue/useconfirm";
import { useToast } from "primevue/usetoast";
import Tag from "primevue/tag";

export default {
  components: { ConfirmDialog, Tag },
  setup() {
    const confirm = useConfirm();
    const toast = useToast();
    const { user } = getUser();
    const input = ref(null);
    const title = ref(null);
    const showVideos = ref(false);
    const { postAVideoUrl } = useAVideos("avideos");
    const { url } = getAVideosUrl();
    const submit = async () => {
      console.log(input.value);
      await postAVideoUrl({
        url: input.value,
        title: title.value,
        createdAt: timestamp(),
        private: false,
        tags: [],
      });
      input.value = null;
      title.value = null;
    };

    const windWidth = ref(null);
    const styleObject = ref(null);

    const urlT = computed(() => {
      if (url.value) {
        return url.value.map((doc) => {
          let time = format(doc.createdAt.toDate(), "PP");
          return { ...doc, createdAt: time };
        });
      }
    });

    onMounted(async () => {
      windWidth.value = window.innerWidth;
      if (windWidth.value > 600) {
        styleObject.value = {
          width: `556px`,
          // height: `240px`,
        };
      } else if (600 > windWidth.value) {
        styleObject.value = {
          width: `285px`,
          // height: `240px`,
        };
      }
    });

    const played = debounce(async () => {
      await profileUpdateField({ key: "avideoPlayed" });
    }, 2500);

    const avideoPage = async () => {
      await profileUpdateField({ key: "avideoPage" });
    };

    const showAVideo = () => {
      confirm.require({
        message:
          "Videos contain Nudity or sexuality, some people may find offensive or disturbing. ",
        header: "Sensitive Content! 18+",
        icon: "pi pi-info-circle",
        acceptClass: "p-button-danger",
        acceptLabel: "Show",
        rejectLabel: "Don't show!",
        accept: () => {
          showVideos.value = true;
          toast.add({
            severity: "info",
            summary: "Confirmed",
            detail: "Videos are open now. Enjoy!",
            life: 4000,
          });
        },
        reject: () => {
          showVideos.value = false;
          toast.add({
            severity: "error",
            summary: "Rejected",
            detail: "You have rejected to watch adult videos.",
            life: 4000,
          });
        },
      });
    };

    const hideAVideo = () => {
      showVideos.value = false;
    };
    return {
      urlT,
      submit,
      input,
      styleObject,
      user,
      title,
      played,
      avideoPage,
      showAVideo,
      showVideos,
      hideAVideo,
    };
  },
  methods: {
    confirmEvent(id) {
      console.log("confirm!");
      projectFirestore
        .collection("avideos")
        .doc(id)
        .delete()
        .then(() => {
          console.log("Document successfully deleted!");
        })
        .catch((error) => {
          console.error("Error removing document: ", error);
        });
    },
    cancelEvent() {
      console.log("cancel!");
    },
  },
};
</script>

<style lang="scss" scoped>
@import url("https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap");

.videos {
  max-width: 600px;
  margin: auto;
}
.ex-video {
  margin-top: 150px;
  margin-bottom: 150px;
}
video {
  max-width: 600px;
}

.btn {
  margin: 0px 0px 50px 0px;
  float: right;
}

.card-box {
  font-family: "Rajdhani", sans-serif;
}

.warn-btn {
  max-width: 600px;
  margin: auto;
}

.ad-btn {
  font-family: "Rajdhani", sans-serif;
  width: 100%;
  margin-top: 50px;
  margin-bottom: 50px;
  height: 60px;
  font-weight: bold;
  font-size: 20px;
  text-transform: uppercase;
}

.p-mr-2 {
  width: 100%;
  margin: auto;
}
</style>
